### ISSUE TITLE
Numpy integer data type support 

### ISSUE THREAD

**Issue by lalapopa** [airinnova/ambiance#10] opened 2022-03-05 14:27 UTC
Hello,
I think it'll be good if Atmosphere class take np.int16 (32) (64) by default. 
For example:
```
np_type_H = np.int16(10000)
air = Atmosphere(H)
```
Gives TypeError :(
```
    raise TypeError("Input data type not accepted")
TypeError: Input data type not accepted
```

**Comment by aarondettmann** [comment] 2022-09-25 15:27
Hello @lalapopa ,

Thanks for your suggestion, and sorry for the lack of responsiveness.

The issue is now fixed and any Numpy data type is now supported:

```python
>>> from ambiance import Atmosphere
>>> import numpy as np
>>>
>>> h = np.int16(10000)
>>> air = Atmosphere(h)
>>> air.density
array([0.41351033])
>>>
```

**Closed as completed by aarondettmann** 2022-09-25 15:27 UTC
